name: 'Lagged Branches'
description: 'Get all branchs lagged and send message to slack'
author: 'Team Devops'
inputs:
  channel_id:
    required: false
    description: 'Add channel'
  thread_ts:
    required: false
    description: 'add thread id'
  max_days:
    required: false
    description: 'add thread id'
    default: '30'
runs:
  using: 'node16'
  main: 'dist/index.js'
