name: 'Lagged Branches'
description: 'Get all branchs lagged and send message to slack'
author: 'Team Devops'
inputs:
  channel_id:
    required: true
    description: 'add channel'
  thread_ts:
    required: false
    description: 'add thread id'
  max_days:
    required: false
    description: 'add max days'
    default: '30'
  deny_branch_list:
    required: false
    description: 'Add list branch validate, separeted with ,'
    default: 'main,release,dependabot'
  delete_branch_list:
    required: true
    description: 'Delete branches'
    default: "false"
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'arrow-right-circle'  
  color: 'blue'
