name: Test

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Repository name'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Error
        run: ls
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: ls
  test:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: "⏬ Check out repository code"
        uses: actions/checkout@v3

      - name: Success
        env:
          RELEASE: ${{ inputs.repo_name }}
        run: |
          git fetch --prune --all
          git checkout ${{ inputs.repo_name }}
          TAG=$(echo $RELEASE | cut -d'/' -f 2)
          git tag $TAG
          git push origin tags/$TAG
          git push -d origin RELEASE
