name: Test

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Error
        run: cat -d
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: ls
  test:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Success
        run: echo "aqui"
