name: 'test'
on:
  workflow_dispatch:

jobs:
  slack:
    runs-on: ubuntu-latest
    outputs:
      thread_ts: ${{ steps.thread_id.outputs.thread_ts }}
    steps:
      - name: Checkout Github
        uses: actions/checkout@v4

      - name: Slack Send Message
        id: thread_id
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        with:
          channel_id: ${{ secrets.CHANNEL_ID }}

  slack-thread:
    runs-on: ubuntu-latest
    needs: slack
    steps:
      - name: Checkout Github
        uses: actions/checkout@v4

      - name: Echo Thread ID
        run: echo ${{ needs.slack.outputs.thread_ts }}

      - name: Slack Send Message in Thread
        uses: ./
        with:
          channel_id: ${{secrets.CHANNEL_ID}}
          thread_ts: ${{ needs.slack.outputs.thread_ts }}
          delete_branch_list: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
